# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gg_sequence_resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GG_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GifA_nr_GG', models.CharField(blank=True, max_length=100)),
                ('graphitisation_Date', models.DateField(blank=True, null=True)),
                ('Operator', models.CharField(blank=True, max_length=50)),
                ('CO2_line', models.CharField(blank=True, max_length=50)),
                ('P_CO2', models.CharField(blank=True, max_length=50)),
                ('weigh_mgC', models.FloatField(blank=True, null=True, verbose_name='weigh (mgC)')),
                ('Measured_P_CO2', models.IntegerField(blank=True, null=True)),
                ('graphitisation_beginning_P', models.DateTimeField(blank=True, null=True)),
                ('expected_Pfin', models.IntegerField(blank=True, null=True)),
                ('Measured_Pfin', models.IntegerField(blank=True, null=True)),
                ('beginning_hour', models.TimeField(blank=True, null=True)),
                ('ending_hour', models.TimeField(blank=True, null=True)),
                ('line_nr', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('iron_mg', models.CharField(blank=True, max_length=200, verbose_name='iron (mg)')),
                ('weighing_operator', models.CharField(blank=True, max_length=50)),
                ('comment_weighing_operator', models.CharField(blank=True, max_length=50)),
                ('press_date', models.DateField(blank=True, null=True)),
                ('press_operator', models.CharField(blank=True, max_length=50)),
                ('comment_operator', models.CharField(blank=True, max_length=50, null=True)),
                ('GG_nr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gg_sequence_resume.gg_sequence_resume')),
            ],
            options={
                'db_table': 'gg_resume',
            },
        ),
    ]
