# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GG_Sequence_Resume',
            fields=[
                ('GG_nr', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('graph', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'gg_sequence_resume',
            },
        ),
    ]
