# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vario_Age3_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(blank=True, max_length=50)),
                ('tin_capsule_lot', models.CharField(blank=True, max_length=50)),
                ('expected_weight', models.CharField(blank=True, max_length=50, verbose_name='expected weight (mg)')),
                ('weighing_operator', models.CharField(blank=True, max_length=50)),
                ('weighing_date', models.DateField(blank=True, null=True, verbose_name='weighing date (DD/MM/YYYY)')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='weight (mg)')),
                ('Vario_measurement_name', models.CharField(blank=True, max_length=50)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('N_area', models.FloatField(blank=True, null=True, verbose_name='N area')),
                ('C_area', models.FloatField(blank=True, null=True, verbose_name='C area')),
                ('n_percent', models.FloatField(blank=True, null=True, verbose_name='N%')),
                ('c_percent', models.FloatField(blank=True, null=True, verbose_name='C%')),
                ('C_N_ratio', models.FloatField(blank=True, null=True, verbose_name='C/N ratio')),
                ('method', models.CharField(blank=True, max_length=200, null=True)),
                ('N_factor', models.FloatField(blank=True, null=True)),
                ('C_factor', models.FloatField(blank=True, null=True)),
                ('N_blk', models.FloatField(blank=True, null=True)),
                ('C_blk', models.FloatField(blank=True, null=True)),
                ('Memo', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('graphitisation_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('age_nr', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'vario_age3_resume',
            },
        ),
    ]
