# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('GifA', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('std_number', models.CharField(blank=True, max_length=250)),
                ('standard_name', models.CharField(blank=True, max_length=250)),
                ('F14C', models.CharField(blank=True, max_length=250)),
                ('uncertainty_F14C', models.CharField(blank=True, max_length=250)),
                ('age', models.CharField(blank=True, max_length=250)),
                ('uncertainty_age', models.CharField(blank=True, max_length=250)),
                ('d13C', models.CharField(blank=True, max_length=250)),
                ('uncertainty_d13C', models.CharField(blank=True, max_length=250)),
                ('material', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('comment', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'standards',
            },
        ),
    ]
