# Generated by Django 3.2.3 on 2021-07-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standards',
            name='GifA',
        ),
        migrations.AlterField(
            model_name='standards',
            name='std_number',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
