# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('lsce_contact', models.BooleanField()),
            ],
            options={
                'db_table': 'people',
                'ordering': ['name'],
            },
        ),
    ]
