# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Station',
            fields=[
                ('work_bench_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('work_bench_description', models.CharField(blank=True, max_length=100, null=True)),
                ('localisation', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'work_station',
            },
        ),
    ]
