# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_acronym', models.CharField(max_length=50)),
                ('project_full_name', models.CharField(blank=True, max_length=250)),
                ('WP_leader', models.CharField(blank=True, max_length=250)),
                ('funding_agency', models.CharField(blank=True, max_length=250)),
                ('student_post_doc_name', models.CharField(blank=True, max_length=250)),
                ('academic_level', models.CharField(blank=True, max_length=250)),
                ('main_supervisor', models.CharField(blank=True, max_length=250)),
                ('second_supervisor', models.CharField(blank=True, max_length=250)),
                ('project_co_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coleader', to='people.people')),
                ('project_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.people')),
            ],
            options={
                'db_table': 'project_list',
            },
        ),
    ]
