# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age3_Sequence_Resume',
            fields=[
                ('age_nr', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('age_graph', models.ImageField(blank=True, null=True, upload_to='')),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('operator_maintenance', models.CharField(blank=True, max_length=50)),
                ('ash', models.IntegerField(blank=True, null=True)),
                ('combustion_colomn', models.IntegerField(blank=True, null=True)),
                ('regenerated_copper_reduction_colomn', models.IntegerField(blank=True, null=True)),
                ('new_copper_reduction_colomn', models.IntegerField(blank=True, null=True)),
                ('sicapent', models.CharField(blank=True, max_length=250, null=True)),
                ('ball_valve', models.FloatField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=250, null=True)),
                ('O2_pressure', models.CharField(blank=True, max_length=250, null=True)),
                ('He_pressure', models.CharField(blank=True, max_length=250, null=True)),
                ('H2_pressure', models.CharField(blank=True, max_length=250, null=True)),
                ('Ar_pressure', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'age3_sequence_resume',
            },
        ),
    ]
