# Generated by Django 3.2.3 on 2021-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age3_sequence_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age3_sequence_resume',
            name='age_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
