# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sequence', '0001_initial'),
        ('work_station', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prep_Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending_date', models.DateField(blank=True, null=True, verbose_name='Ending date (DD/MM/YYYY)')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.people')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sequence.sequence')),
                ('work_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_station.work_station')),
            ],
            options={
                'db_table': 'prep_step',
            },
        ),
    ]
