# Generated by Django 3.2.3 on 2021-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_sample_gifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='collec_science',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
