# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('age3_sequence_resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age3_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GifA_nr_age3', models.CharField(blank=True, max_length=100)),
                ('total_sample_weight', models.FloatField(blank=True, null=True, verbose_name='total sample weight (mg)')),
                ('CO2_ug', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CO2/ug')),
                ('CO2fin_ug', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CO2fin/ug')),
                ('COH2_mbar', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='COH2/mbar')),
                ('Time_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Time/min')),
                ('C_percent', models.FloatField(blank=True, null=True, verbose_name='C%')),
                ('T_celsius', models.IntegerField(blank=True, null=True, verbose_name='T/°C')),
                ('Tset_celsius', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Tset/°C')),
                ('p_end_mbar', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='p_end/mbar')),
                ('Sample_date_age3', models.DateTimeField(blank=True, max_length=50, null=True, verbose_name='Sample_date_age3')),
                ('N_percent', models.FloatField(blank=True, max_length=50, null=True, verbose_name='N%')),
                ('reactor', models.IntegerField(blank=True, null=True)),
                ('tin_capsule_nr', models.IntegerField(blank=True, null=True)),
                ('pre_or_not', models.BooleanField(blank=True, null=True)),
                ('graphitisation_operator', models.CharField(blank=True, max_length=50)),
                ('graphitisation_comment', models.CharField(blank=True, max_length=250)),
                ('iron_mg', models.FloatField(blank=True, null=True, verbose_name='iron (mg)')),
                ('weighing_operator', models.CharField(blank=True, max_length=50)),
                ('comment_weighing_operator', models.CharField(blank=True, max_length=50)),
                ('press_date', models.DateField(blank=True, null=True)),
                ('press_operator', models.CharField(blank=True, max_length=50)),
                ('comment_press_operator', models.CharField(blank=True, max_length=50)),
                ('age_nr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='age3_sequence_resume.age3_sequence_resume')),
            ],
            options={
                'db_table': 'age3_resume',
            },
        ),
    ]
