# Generated by Django 3.2.3 on 2021-07-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age3_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age3_resume',
            name='Tset_celsius',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tset/°C'),
        ),
        migrations.AlterField(
            model_name='age3_resume',
            name='p_end_mbar',
            field=models.IntegerField(blank=True, null=True, verbose_name='p_end/mbar'),
        ),
    ]
