# Generated by Django 3.2.3 on 2021-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('sequence_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'sequence',
            },
        ),
    ]
